#!/usr/bin/env bash
# Bash script that receives a domain and a subdomain and outputs the subdomain, record type and the IP that points to
if (( $# < 2))
then
	subdom1=www.$1
	subdom2=lb-01.$1
	subdom3=web-01.$1
	subdom4=web-02.$1
	record1=$(dig "$subdom1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
	destination1=$(dig "$subdom1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
	echo The subdomain "$subdom1" is a "$record1" record and points to "$destination1"
	record2=$(dig "$subdom2" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
	destination2=$(dig "$subdom2" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
	echo The subdomain "$subdom2" is a "$record2" record and points to "$destination2"
	record3=$(dig "$subdom3" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
	destination3=$(dig "$subdom3" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
	echo The subdomain "$subdom3" is a "$record3" record and points to "$destination3"
	record4=$(dig "$subdom4" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
	destination4=$(dig "$subdom4" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
	echo The subdomain "$subdom4" is a "$record4" record and points to "$destination4"
else
	subdom=$2.$1
	record=$(dig "$subdom" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
	destination=$(dig "$subdom" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
	echo The subdomain "$subdom" is a "$record" record and points to "$destination"
fi
