#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
