#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine with a redirection
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx start
sed -i "42i\ \trewrite ^/redirect_me/* https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
