#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine with a redirection
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i "42i\ \trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
