#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine with a redirection
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/error404.html
echo "Ceci n'est pas une page " > /var/www/html/error404.html
echo "" >> /var/www/html/error404.html
sudo sed -i "37i\ \tlocation /redirect_me/ {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}" /etc/nginx/sites-available/default
sudo sed -i "38i\ \terror_page 404 /error404.html;" /etc/nginx/sites-available/default
sudo service nginx start
