#!/usr/bin/env bash
# Script that configure nginx with custom HTTP header
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "46i\ \tadd_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start
