#!/usr/bin/env bash
# Script that configure load balancer with HAproxy
sudo apt-get update
sudo apt-get install -y haproxy=1.5\*
sudo sed -i "$ a ENABLE=1" /etc/default/haproxy
sudo sed -i "$ a frontend http_front" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tbind *:80" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tdefault_backend http_back" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a backend http_back" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tbalance roundrobin" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tserver 2267-web-01 35.227.67.236:80 check" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tserver 2267-web-02 35.231.147.151:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy reload
sudo systemctl restart haproxy
