#!/usr/bin/env bash
# Bash script that configures a server to listen to port 80
rm /etc/nginx/sites-enabled/default | ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx reload
service nginx restart
service nginx stop