#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=1
while [ $counter -le 10 ]
do
    if [ $counter == '10' ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    ((counter++))
done
