#!/usr/bin/env bash
# This script gives you information about the holbertonschool file.
a=0
file="$(ls)"
for i in $file; do

    if [ "$i" == 'holbertonschool' ]; then
        echo "holbertonschool file exists"
        a=1
        if [ -s "$i" ]; then
            echo "holbertonschool file is not empty"
        else 
            echo "holbertonschool file is empty"
        fi
        if [ -f "$i" ]; then
            echo "holbertonschool is a regular file"
        fi
        continue
    fi
done

if [ $a == '0' ]; then
    echo "holbertonschool file does not exist"
fi
